#!/bin/bash

set -e
# Checkout the release branch
git checkout releases/beta

# Get this branch even with master so the latest changes are included
git reset --hard master

# Rerun the checks and rebuild the TypeScript and ncc distribution
npm run build

# Add the dist
git add .

# Commit
git commit -m "beta"

# Force push to overwrite any previous commits for this branch
git push -f origin releases/beta

# Remove previously pushed tags (beta will be unusable momentarily until you re-push)
git push origin :refs/tags/beta

# Re-apply the tag
git tag -fa beta -m "beta"

# Push everything
git push origin beta

# Checkout master again
git checkout master
